from sys import argv
#first input then output
p=int(input("Enter value"))
q=float(input('enter float value'))
print("P+Q===",p+q)
print("\n\n\n`~~~~~~``~~~~~````~~~~~~~~~[One line uer input and addition ]`~~~~~~``~~~~~````~~~~~~~~~\n\n\n")
print("pp+qq:;:",int(input('enter_pp'))+int(input('enter_qq')))
print("\n\n\n`~~~~~~``~~~~~````~~~~~~~~~[program for employ data ]`~~~~~~``~~~~~````~~~~~~~~~\n\n\n")
eno=int(input("ENTER EMPLOYE NUMBER"))
ename=input("ENTER EMPLOYE NAME")
esal=float(input("ENTER EMPLOYE SALARY"))
eadd=input("EMPLOY ADDRESS")
print("\nEMPLOYE NUMBER->",eno)
print("\nEMPLOYE NAME->",ename)
print("\nEMPLOYE SALARY->",esal)
print("\nEMPLOY ADDRESS->",eadd)
print("\n\n\n`~~~~~~``~~~~~````~~~~~~~~~[read multipal value from kyebord in one line ]`~~~~~~``~~~~~````~~~~~~~~~\n\n\n")
a,b,cd,ed=[int(i)for i in input("enter value").split('~')]
print("Sum =",a+b+cd+ed)
print("\n\n\n`~~~~~~``~~~~~````~~~~~~~~~[eperiment on eval()function ]`~~~~~~``~~~~~````~~~~~~~~~\n\n\n")
test_0=eval(input("enter some expression"))
print("type of test_0=",type(test_0),"value of test=",test_0)
test_1=eval(input("enter some value"))
print("type of test_0=",type(test_1),"value of test=",test_1)
print("\n\n\n`~~~~~~``~~~~~````~~~~~~~~~[read multipal value from kyebord in one line on eperiment on eval()function ]`~~~~~~``~~~~~````~~~~~~~~~\n\n\n")
v,n,m=[eval(u)for u in input("enter 3 value").split()]
print("type of v:",type(v)," valur of v",v)
print("type of n:",type(n)," valur of n",n)
print("type of m :",type(m)," valur of m",m)
print("\n\n\n`~~~~~~``~~~~~````~~~~~~~~~[command line argument]`~~~~~~``~~~~~````~~~~~~~~~\n\n\n")
print("type of argv:",type(argv))
print("print argv:",argv)
